// react-app/src/components/header.js
import React, { Component } from 'react';


class header extends Component {
    render() {
        return (
            <div className="header">
                <img className="logo__img" src={'/img/top-logo.png'} alt="Can't find img"></img>
                <div className="nav">
                    <ul className="nav__ul">
                        <li className="nav__li">
                            <a className="nav__link" href="/">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        );
    }
}

export default header;

// arne-johannesen/src/Header.vue
<template>
    <div class="header">
        <img class="logo__img" src='./assets/top-logo.png' alt="Can't find img">
        <div class="nav">
            <ul class="nav__ul">
                <li class="nav__li">
                    <a class="nav__link" href="/">Home</a>
                </li>
            </ul>
        </div>
    </div>
</template>


<style lang="scss" scoped>
    .header{
        background: #68b6f0;
    }

    .logo__img{
        width: 500px;
        padding-left: 30px;
    }

    .nav{
        background: #5C708E;
        display: flex;
        flex-direction: column;
        justify-content: center;

        &__li{
            list-style: none;
            float: left;
            font-size: 20px;
            padding-right: 20px;
        }

        &__link{
            color: white;
        }
    }

</style>


<script>
export default {
    data(){
        return{

        }
    }
}
</script>
